name: Fetch Plannings

on:
  schedule:
    - cron: '0 8 * * *' # tous les jours à 8h
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Write secrets to files
        run: |
          echo "${{ secrets.GMAIL_TOKEN }}" > token.json
          echo "${{ secrets.GMAIL_CREDENTIALS }}" > credentials.json

      - name: Run script
        run: python fetch_plannings.py

      - name: Upload plannings
        uses: actions/upload-artifact@v4
        with:
          name: plannings
          path: plannings.json
